# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92ef8b055a9bc1ae837f83148cd86cbe1a6ba796133a99f3a2ce7251cbfd730f3bf82ecafefb0239962bb95177a156f331b9477f1066a1d3889feb8e6ca0e76c

test:
  secret_key_base: 76e6b06855aa99c692059db018eeb648e8ac86684f3c3dd6bc94b66fb7c268ad20974d68a4593bde980969f7a41ce289a7d2b0c40cd7cf114251cbf89e959f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
